### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by PixellUp** [etozhealkhipce/editorjs-aitext#1]
There seems to be an issue trying to install and use it as a tool. What I get when installing the package and configuring it in `EditorJs` tools section is that

```shell
[vite] Internal server error: Failed to resolve entry for package "@alkhipce/editorjs-aitext". The package may have incorrect main/module/exports specified in its package.json.
  Plugin: vite:import-analysis
``` 

Packages: 
`EditorJs: 2.28.2`
`editorjs-aitext: 1.0.2`

**Comment by etozhealkhipce** [comment]
Could you send your code using something like [CodeSandbox](https://codesandbox.io/) for reproduction?

Thanks

**Comment by PixellUp** [comment]
That's interesting. I'm using a bit old version of Vite "3.2.7" that is causing the issue. On CodeSandbox with Vite "4.5." an above the issue is non exististant.

Updating the Vite,do resolve the import issue, however with provided OpenAI token, it does not seams to "work" by generating a shorter text. Attacking a link to [CodeSanbox](https://codesandbox.io/p/sandbox/polished-hooks-dj9mn5?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clouce51h00072e676dhh5wm4%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clouce51h00032e67j7k78c9y%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clouce51h00052e675admsfcv%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clouce51h00062e67rgeryhwm%2522%257D%252C%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cloucm23003kj2e670wt7wter%2522%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%255D%252C%2522sizes%2522%253A%255B60%252C40%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clouce51h00032e67j7k78c9y%2522%253A%257B%2522id%2522%253A%2522clouce51h00032e67j7k78c9y%2522%252C%2522activeTabId%2522%253A%2522cloucg6mh01172e67h2akundi%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clouce51g00022e67502gl62e%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.js%2522%252C%2522id%2522%253A%2522cloucfrdm00q32e670hhogjsb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522id%2522%253A%2522cloucg6mh01172e67h2akundi%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.html%2522%252C%2522id%2522%253A%2522cloucihs5029m2e67obrhc91y%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsandbox.config.json%2522%252C%2522id%2522%253A%2522cloucsht805722e67jh49xizh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clouce51h00062e67rgeryhwm%2522%253A%257B%2522id%2522%253A%2522clouce51h00062e67rgeryhwm%2522%252C%2522activeTabId%2522%253A%2522cloucupj806mb2e676q0gz67i%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A5000%252C%2522id%2522%253A%2522cloucebvh00by2e67an7eeda0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522cloucnmvp046a2e67ewk4zhzx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A5174%252C%2522id%2522%253A%2522cloucupj806mb2e676q0gz67i%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clouce51h00052e675admsfcv%2522%253A%257B%2522id%2522%253A%2522clouce51h00052e675admsfcv%2522%252C%2522activeTabId%2522%253A%2522cloucule606jd2e670zvu32om%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cloucsqop05br2e67ht2ya1k0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cloucsqs00007eeg1fev7armj%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522cloucszwq05jl2e6779lvoyoc%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522id%2522%253A%2522cloucule606jd2e670zvu32om%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clouculhl0009eeg17ur02e5b%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522yarn%2520add%2520vite%2540latest%2520--dev%2522%252C%2522id%2522%253A%2522cloucuvkt06pu2e67sqx8rqo3%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522cloucm23003kj2e670wt7wter%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cloucm1wi03kg2e67i14eaozd%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A5000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cloucm23003kj2e670wt7wter%2522%252C%2522activeTabId%2522%253A%2522cloucm1wi03kg2e67i14eaozd%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) 

**^ Need a Vite version ^4.5 or above to work**

**Comment by etozhealkhipce** [comment]
@PixellUp 
Can you make sure you added the AIText component from Editor.js Toolbox?

I have checked your example and everything is working with `Vite 4.5 ` for me

![image](https://github.com/etozhealkhipce/editorjs-aitext/assets/38625168/d210405e-4fd0-4722-9452-91ff734ffb3f)



Also I will try to make  package workable with older versions Vite soon

**Comment by PixellUp** [comment]
I'll close this issue as it seems it's something on my end. Thanks for the effort @etozhealkhipce
