### ISSUE TITLE
Unable to Resolve '@alkhipce/editorjs-aitext' Module and Bundle Size Unavailable

### ISSUE THREAD

**Issue by GanonForce** [etozhealkhipce/editorjs-aitext#2]
Hello,

I'm encountering an issue while attempting to import the '@alkhipce/editorjs-aitext' module in my project. The error message I'm receiving is:

Module not found: Error: Can't resolve '@alkhipce/editorjs-aitext' in '/src/src/components/Editor'
Additionally, when checking the bundle size using Bundlephobia [link](https://bundlephobia.com/package/@alkhipce/editorjs-aitext), the platform couldn't find the entry point.
<img width="1728" alt="image" src="https://github.com/etozhealkhipce/editorjs-aitext/assets/43139652/c427470c-1557-456a-9b2a-349db538f239">

I have ensured that the package is installed correctly and it appears to have the latest version.

Could you please assist me in understanding the correct import approach or provide guidance on resolving this issue? I've checked the documentation, but I seem to be missing something in the import process.

Thank you for your help!

Best regards,
Alexander

**Comment by etozhealkhipce** [comment]
Hello, thanks for you issue!

I will try to fix it today.

**Comment by etozhealkhipce** [comment]
I have fixed that in last commit.
Sorry for waiting.
