### ISSUE TITLE
What's the point of exposing the OpenAI API key on the frontend?

### ISSUE THREAD

**Issue by geekyayush** [etozhealkhipce/editorjs-aitext#3]
While this is a great extension to Editor.js, I am unable to understand the fact that it needs me to expose the OpenAI API key on the frontend where the editor lies. Having the key implemented like this also goes against OpenAI standards.

Maybe a callback function that allows the developer to have their own OpenAI or any other provider API implementation would be a better choice. In the callback function, a developer can call their backend which then calls OpenAI API.

What are your thoughts?

**Comment by etozhealkhipce** [comment]
Great idea, thanks!
I will try implement this feature as soon as I get some free time.
