### ISSUE TITLE
[FEAT] add a way to provide a training model (or texts) for the ai result

### ISSUE THREAD

**Issue by Aarbel** [etozhealkhipce/editorjs-aitext#5]
Is there a way to provide some texts blocks or context, so openai can give better results ?

**Comment by etozhealkhipce** [comment]
Hello!

If I understood you correct. you might be able to do so throught "controlled component"-ish way.
You can save the result from, let's say, your backend and pass it into the extention. 
The package itself does not work with context separately.

**Comment by Aarbel** [comment]
@etozhealkhipce 

My question was about this:

- to provide qualitative texts suggestions, is that possible to pass to this plugin some "pre-trainer" open ai profile or login ?
